# Generated by Django 5.1.3 on 2024-11-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdocument',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
