# Generated by Django 5.1.3 on 2024-11-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdocument',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
