# Generated by Django 5.1.3 on 2024-12-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_serverdocument_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdocument',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
